### ISSUE TITLE
Ipad pro, Ipad air could not show the smart banner

### ISSUE THREAD

**Issue by qingbolove** [adjust/smart_banner_sdk#17]
We are integrating smart banner SDK to our code base, we are working on testing now, and now we found Ipad pro, Ipad air could not show the smart banner, it report "Can't show banner, you should initialise Smart Banner SDK first", but Ipad min could work perfectly without error message, iphone 12, iphone 13 could work as well, just the exactly same code! So please help to check why ? Thanks
![image](https://github.com/adjust/smart_banner_sdk/assets/10628904/c4285b4e-92ba-4334-8339-2bb13d376aec)

**Comment by qingbolove** [comment]
iPad min could work
<img width="1863" alt="image" src="https://github.com/adjust/smart_banner_sdk/assets/10628904/2761beee-1a60-434f-b8a5-176283e15d9d">

**Comment by YaraMatkova** [comment]
Hi @qingbolove 👋 

Could you please set [log level](https://github.com/adjust/smart_banner_sdk/?tab=readme-ov-file#loglevel-string) `verbose` in SDK initialisation like this
```
AdjustSmartBanner.init({
  logLevel: "verbose",
})
```
so we could probably see what's going wrong on iPad Pro?

And could you also log userAgent of your testing browser and share the result?
```
console.log(navigator.userAgent);
```

**Comment by qingbolove** [comment]
How could I get the log, do you have a wiki to follow?

**Comment by YaraMatkova** [comment]
Hey @qingbolove,

To get verbose log please add `logLevel: "verbose"` to your SDK initialisation as it shown in the comment above.

Based on screenshots I assume you use desktop Chromium-based browser for testing, so you can find the logs on Console tab in browser development tools.

**Comment by qingbolove** [comment]
![image](https://github.com/adjust/smart_banner_sdk/assets/10628904/4688285e-4542-4338-b4e8-c70f2719418b)
Sorry, no, we do not have Chromium-based browser for Xiaomi, we use real device

**Comment by YaraMatkova** [comment]
Um. Let me remind that issue you created has title "Ipad pro, Ipad air could not show the smart banner" 🙂

Actually I suppose the issue with the iPads is related to their user agents. The SDK [relies on the user agent](https://github.com/adjust/smart_banner_sdk/blob/main/sdk/src/utils/detect-os.ts), but these devices user agents are the same as ones of desktop browser. Looks like an SDK bug, we will fix it and update you here, once the fix is released.

Regarding Xiaomi Browser, hopefully this article [Remote debug Android devices](https://developer.chrome.com/docs/devtools/remote-debugging/) could be useful.

Also I would recommend to merge `init({/*...*/})` calls in one and make it independent of `common.isIos` function, since the SDK detects the platform itself and uses only needed arguments
```
const iosPath = ""; // your code to get iOS deep link path
const androidPath = "";  // your code to get Android deep link path

AdjustSmartBanner.init({
  appToken: {
    ios: adjustIosWebToken,
    android: adjustAndroidWebToken
  },
  iosDeepLinkPath: iosPath,
  androidDeepLinkPath: androidPath,
  language: lang,
  bannerParent: element,
  logLevel: "verbose",
  onDismissed: () => this.close()
})
```

**Comment by YaraMatkova** [comment]
Hi @qingbolove, I'm going to close this. Feel free to comment, reopen this issue, or create a new one if you have additional questions. All the best!
